apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: example
spec:
  ports:
  - name: db
    protocol: TCP
    port: 5432
    targetPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: db-headless
  namespace: example
spec:
  clusterIP: None
  selector:
    app: backend
  ports:
  - port: 5000
    targetPort: 5000

---
apiVersion: v1
kind: Endpoints
metadata:
  name: db
  namespace: example
subsets:
- addresses:
  - ip: 10.244.0.10
  ports:
  - port: 5432
    protocol: TCP