apiVersion: v1
kind: Service
metadata:
  name: my-nodeport-service
  namespace: default
spec:
  type: NodePort
  ports:
  - name: http
    nodePort: 30000
    port: 5000
    targetPort: 5000
    protocol: TCP
  selector:
    app: hello-world-flask
